# Generated by Django 4.2.9 on 2024-01-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
