# Generated by Django 4.2.9 on 2024-03-02 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_api', '0005_esp32device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
