# Generated by Django 4.2.9 on 2024-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_api', '0006_esp32device_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp32device',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='esp32device',
            name='is_switched',
            field=models.BooleanField(default=False),
        ),
    ]
