# Generated by Django 4.2.9 on 2024-03-20 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_api', '0007_remove_esp32device_last_seen_esp32device_is_switched'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='switching_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
